package com.jny.common.fragment;

public interface FragmentConstants {
    String FISH_TEST_FRAGMENT_ID = "FISH_TEST_FRAGMENT_ID";
    String VERTICAL_DRAWER_RECYCLERVIEW_TEST_FRAGMENT_ID = "VERTICAL_DRAWER_RECYCLERVIEW_TEST_FRAGMENT_ID";
    String LAZY_TEST_FRAGMENT_ID = "LAZY_TEST_FRAGMENT_ID";
    String MATERIAL_DESIGN_TEST_ID = "MATERIAL_DESIGN_TEST_ID";
    String TEXT_TEST_FRAGMENT_ID = "TEXT_TEST_FRAGMENT_ID";
    String MATERIAL_VIEW_TEST_FRAGMENT_ID = "MATERIAL_VIEW_TEST_FRAGMENT_ID";
    String NESTED_SCROLL_VIEW_TEST_FRAGMENT_ID = "NESTED_SCROLL_VIEW_TEST_FRAGMENT_ID";
    String FULL_SCREEN_DIALOG_TEST_FRAGMENT_ID = "FULL_SCREEN_DIALOG_TEST_FRAGMENT_ID";
    String CUSTOM_NESTED_SCROLL_VIEW_TEST_FRAGMENT_ID = "CUSTOM_NESTED_SCROLL_VIEW_TEST_FRAGMENT_ID";
    String DRAWER_LAYOUT_TEST_FRAGMENT_ID = "DRAWER_LAYOUT_TEST_FRAGMENT_ID";
    String LONG_VIEW_IMAGE_TEST_FRAGMENT_ID = "LONG_VIEW_IMAGE_TEST_FRAGMENT_ID";
    String CUSTOM_LAYOUT_MANAGER_TEST_FRAGMENT_ID = "CUSTOM_LAYOUT_MANAGER_TEST_FRAGMENT_ID";
    String PHOTO_VIEW_TEST_FRAGMENT_ID = "PHOTO_VIEW_TEST_FRAGMENT_ID";
    String GRID_IMAGE_LAYOUT_TEST_FRAGMENT_ID = "GRID_IMAGE_LAYOUT_TEST_FRAGMENT_ID";
    String SLIDE_MENU_TEST_FRAGMENT_ID = "SLIDE_MENU_TEST_FRAGMENT_ID";
    String COORDINATE_TEST_FRAGMENT_ID = "COORDINATE_TEST_FRAGMENT_ID";
    String PROGRESS_TEST_FRAGMENT_ID = "PROGRESS_TEST_FRAGMENT_ID";
    String RATING_BAR_FRAGMENT_ID = "RATING_BAR_FRAGMENT_ID";
    String LETTER_FRAGMENT_ID = "LETTER_FRAGMENT_ID";
    String MVPS_TEST_FRAGMENT_ID = "MVPS_TEST_FRAGMENT_ID";
    String CUSTOM_TEST_HANDLER_ID = "CUSTOM_TEST_HANDLER_ID";
    String MVVM_TEST_FRAGMENT_ID = "MVVM_TEST_FRAGMENT_ID";
}
