package com.jny.common.fragment;

public interface FragmentConstants {
    String FRAGMENT = "FRAGMENT";
    String ACTIVITY = "ACTIVITY";
    String CUSTOM_VIEW = "app";
    String FISH_TEST_FRAGMENT_ID = "FISH_TEST_FRAGMENT_ID";
    String VERTICAL_DRAWER_RECYCLERVIEW_TEST_FRAGMENT_ID = "VERTICAL_DRAWER_RECYCLERVIEW_TEST_FRAGMENT_ID";
    String LAZY_TEST_FRAGMENT_ID = "LAZY_TEST_FRAGMENT_ID";
    String MATERIAL_DESIGN_TEST_ID = "MATERIAL_DESIGN_TEST_ID";
    String TEXT_TEST_FRAGMENT_ID = "TEXT_TEST_FRAGMENT_ID";
    String MATERIAL_VIEW_TEST_FRAGMENT_ID = "MATERIAL_VIEW_TEST_FRAGMENT_ID";
    String NESTED_SCROLL_VIEW_TEST_FRAGMENT_ID = "NESTED_SCROLL_VIEW_TEST_FRAGMENT_ID";
    String FULL_SCREEN_DIALOG_TEST_FRAGMENT_ID = "FULL_SCREEN_DIALOG_TEST_FRAGMENT_ID";
    String CUSTOM_NESTED_SCROLL_VIEW_TEST_FRAGMENT_ID = "CUSTOM_NESTED_SCROLL_VIEW_TEST_FRAGMENT_ID";
    String DRAWER_LAYOUT_TEST_FRAGMENT_ID = "DRAWER_LAYOUT_TEST_FRAGMENT_ID";
    String LONG_VIEW_IMAGE_TEST_FRAGMENT_ID = "LONG_VIEW_IMAGE_TEST_FRAGMENT_ID";
    String CUSTOM_LAYOUT_MANAGER_TEST_FRAGMENT_ID = "CUSTOM_LAYOUT_MANAGER_TEST_FRAGMENT_ID";
    String PHOTO_VIEW_TEST_FRAGMENT_ID = "PHOTO_VIEW_TEST_FRAGMENT_ID";
    String GRID_IMAGE_LAYOUT_TEST_FRAGMENT_ID = "GRID_IMAGE_LAYOUT_TEST_FRAGMENT_ID";
    String SLIDE_MENU_TEST_FRAGMENT_ID = "SLIDE_MENU_TEST_FRAGMENT_ID";
    String COORDINATE_TEST_FRAGMENT_ID = "COORDINATE_TEST_FRAGMENT_ID";
    String PROGRESS_TEST_FRAGMENT_ID = "PROGRESS_TEST_FRAGMENT_ID";
    String RATING_BAR_FRAGMENT_ID = "RATING_BAR_FRAGMENT_ID";
    String LETTER_FRAGMENT_ID = "LETTER_FRAGMENT_ID";
    String CIRCLE_BOTTOM_SHEET_DIALOG_FRAGMENT = "CIRCLE_BOTTOM_SHEET_DIALOG_FRAGMENT";
    String BACKGROUND_TINT_TEST_FRAGMENT = "BACKGROUND_TINT_TEST_FRAGMENT";

    String MVPS_TEST_FRAGMENT_ID = "MVPS_TEST_FRAGMENT_ID";
    String CUSTOM_TEST_HANDLER_ID = "CUSTOM_TEST_HANDLER_ID";
    String MVP_TEST_FRAGMENT_ID = "MVP_TEST_FRAGMENT_ID";
    String MVVM_TEST_FRAGMENT_ID = "MVVM_TEST_FRAGMENT_ID";
    String DOWNLOAD_BITMAP_TEST_FRAGMENT_ID = "DOWNLOAD_BITMAP_TEST_FRAGMENT_ID";

    String SCROLL_PRELOAD_TEXT_FRAGMENT_ID = "SCROLL_PRELOAD_TEXT_FRAGMENT_ID";
    String SECOND_FLOOR_REFRESH_LAYOUT = "SECOND_FLOOR_REFRESH_LAYOUT";

    String DYNAMIC_WEB_VIEW_ACTIVITY_ID = "DYNAMIC_WEB_VIEW_FRAGMENT_ID";
    String REACT_NATIVE_FRAGMENT_ID = "REACT_NATIVE_FRAGMENT_ID";
    String REACT_NATIVE_SECOND_FLOOR = "REACT_NATIVE_SECOND_FLOOR";
    String STITCHING_ANIMATION_FRAGMENT_ID = "STITCHING_ANIMATION_FRAGMENT_ID";
    String STITCHING_IMAGE_FRAGMENT_ID = "STITCHING_IMAGE_FRAGMENT_ID";
    String STITCHING_VIDEO_FRAGMENT_ID = "STITCHING_VIDEO_FRAGMENT_ID";
    String STITCHING_TEXTURE_VIDEO_FRAGMENT_ID = "STITCHING_TEXTURE_VIDEO_FRAGMENT_ID";
    String SWIPE_GUIDE_FRAGMENT_ID = "SWIPE_GUIDE_FRAGMENT_ID";
    String VIEW_POST_TEST_FRAGMENT_ID = "VIEW_POST_TEST_FRAGMENT_ID";
    String KT_DSL_TEST_FRAGMENT_ID = "KT_DSL_TEST_FRAGMENT_ID";
    String ROOM_DB_FRAGMENT_ID = "ROOM_DB_FRAGMENT_ID";
    String DYNAMIC_THEME_FRAGMENT_ID = "DYNAMIC_THEME_FRAGMENT_ID";

    String PERFORMANCE_AUTO_CHANGE_STYLE_ID = "PERFORMANCE_AUTO_CHANGE_STYLE_ID";
}
